HW1: Design doc
FrogOfJuly/rogue-like pull request #1
Opened 2021-04-04 22:54 UTC by krikun98

В основном док в notion, но исходники некоторых диаграмм в репозитории.
Ссылка в `readme`, дублирую [тут](https://www.notion.so/c751085ebb244bcf8942cf17ddce652b).

2021-04-04 22:56 UTC, krikun98 commented
Готовы пока более общие описания, диаграммы классов и распределение обязанностей добавим, когда начнём реализацию и станут более понятны некоторые моменты.

2021-04-15 06:50 UTC, FirstTimeInForever requested changes
Выглядит модно.

* На диаграммах компонентов не указаны интерфейсы, связывающие компоненты.

Вообще, не очень понятно, почему бы не написать сервер тоже на питоне. Да и вообще зачем поддерживать мультиплеер, если в этой задаче он не требуется. Хотя, кажется, что это и не сильно сложно, учитывая то, что игра не real time.

Будет клёво, если вы сервер и клиент завернёте в докер контейнер (можно в несколько, но тогда положите ещё `docker-compose.yml`).

`5/6`.

2021-04-15 08:37 UTC, krikun98 commented
> Выглядит модно.

Спасибо!

> * Нет диаграмм классов

Обязательно добавим, планировали как раз сделать, как будет первая реализация. В принципе наброски уже готовы, сделаем в субботу. Я же правильно понимаю, что это единственный недочёт на баллы?

> Вообще, не очень понятно, почему бы не написать сервер тоже на питоне. Да и вообще зачем поддерживать мультиплеер, если в этой задаче он не требуется. Хотя, кажется, что это и не сильно сложно, учитывая то, что игра не real time.

Про сервер на плюсах лучше ответит @FrogOfJuly, он очень хотел жёсткую систему типов в движке. Ну а про мультиплеер - требование на будущее, которое озвучивалось сразу, ещё до начала проекта. Никаких особых телодвижений для поддержки именно мультиплеера к первому дедлайну не планируется, просто пусть будет. Добавить его в нашей архитектуре и правда будет несложно.

2021-04-15 08:39 UTC, FirstTimeInForever commented
> Я же правильно понимаю, что это единственный недочёт на баллы?

Да.

2021-04-15 13:41 UTC, FrogOfJuly commented
Я руководствовался тем, что сложные системы хорошо писать на чем-то, где компилятор все-таки проверяет типы как-то. Именно плюсы, а не java или что-то аналогичное, потому что я уже прокидывал мостик между питоном и плюсами. 
Ну и кажется что если делать вид что мы по настоящему  игру разрабатываем, то обычно это все-таки на плюсах делается. Питон был добавлен потому что на нем есть куча библиотек для сетевого взаимодействия и, наверное, для отрисовки в консольной графике

2021-04-22 18:02 UTC, FrogOfJuly commented
> > Я же правильно понимаю, что это единственный недочёт на баллы?
> 
> Да.

В ноушене теперь есть диаграмма классов

2021-05-01 22:05 UTC, FirstTimeInForever reviewed
Что-то я абсолютно не понял эту "диаграмму классов". Зачем какие-то сущности собраны в прямоугольники? Почему композиция отображена на этих прямоугольниках, а не на самих сущностях? Не понятно что происходит с `Components` и `Entities`. Ожидалось что-то [хоть немного похожее на это](https://circle.visual-paradigm.com/wp-content/uploads/2017/08/Class-Diagram-Telephone-Use-of-Association-2.png).

Предположим что я таки смог распарсить вашу диаграмму. Зачем `Potion` имеет `health`? Зачем он умеет атаковать и уж тем более передвигаться? Очень не очевидно что с чем имеет связи.

Короче говоря, это не годится.

2021-05-01 22:06 UTC, FirstTimeInForever commented
`5/6`.

2021-05-01 22:06 UTC, closed without merging